title: "Yuriy Sverchkov"
theme: jekyll-theme-minimal
logo: https://avatars.githubusercontent.com/u/2293026?v=4
description: Assistant Scientist at the Department of Biostatistics and Medical Informatics, University of Wisconsin - Madison

collections:
  projects:
    output: true
    layout: default
    order:
      - tree-xai.md
      - metadata-standardization.md
  past_projects:
    output: true
    order:
      - nem.md
      - edapd.md
      - cluser-dp.md
      - pa-oh-big.md