title: "Yuriy Sverchkov"
theme: jekyll-theme-minimal
logo: https://avatars.githubusercontent.com/u/2293026?v=4
description: Assistant Scientist at the Department of Biostatistics and Medical Informatics, University of Wisconsin - Madison

excerpt_separator: <!--more-->

collections:
  - projects
  - past_projects